module.exports = {
  dataServiceUrl: process.env.DATA_SERVICE_URL || 'http://localhost:4730',
  analyticsServiceUrl: process.env.ANALYTICS_URL || 'http://localhost:5555',
  accountsUrl: process.env.ACCOUNTS_URL || 'http://localhost:1447/',
  cacheAppPrefix: 'app',
  cacheSchemaPrefix: 'schema',
  globalDb: '_GLOBAL',
  globalSettings: '_Settings',
  schemaExpirationTimeFromCache: 86400,
  mandrill: process.env.MANDRILL,
  mixpanelToken: process.env.MIXPANEL_TOKEN,
  mailchimpApiKey: process.env.MAILCHIMP_API_KEY,
  logToken: process.env.LOG_TOKEN,
  mailGunApiKey: process.env.MAILGUN_API_KEY,
  mailGunDomain: process.env.MAIL_GUN_DOMAIN,
  adminEmailAddress: process.env.ADMIN_EMAIL,
  herokuUsername: process.env.HEROKU_USERNAME,
  herokuPassword: process.env.HEROKU_PASSWORD,
  herokuSalt: process.env.HEROKU_SALT,
  sendgridApiKey: process.env.SENDGRID_API_KEY,
  slackWebHook: process.env.SLACK_WEBHOOK,
  stripeSecureKey: process.env.STRIPE_SECURE_KEY,
  stripeEndpointSecret: process.env.STRIPE_ENDPOINT_SECRET || 'whsec_4GxoaQBfH3P2P31DqQzP3X1fQrkCBqwq',
};
