module.exports = function () {
  return {
    plans: [
      {
        id: 1,
        price: '00.00',
        amount: 0,
        planName: 'Free Plan',
        interval: 'forever',
        apiCalls: 2500,
        storage: 0.2,
        connections: 100,
        mongoDbAccess: false,
      }, {
        id: 2,
        price: '49.00',
        amount: 49,
        planName: 'launch-plan',
        interval: 'month',
        apiCalls: 250000,
        storage: 5,
        connections: 500,
        mongoDbAccess: true,
      }, {
        id: 3,
        price: '99.00',
        amount: 99,
        planName: 'scale-plan',
        interval: 'month',
        apiCalls: 1000000,
        storage: 10,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      }, {
        id: 4,
        price: '700.00',
        amount: 700,
        planName: 'CloudBoost Pro Plus Monthly',
        interval: 'month',
        apiCalls: 10000000,
        storage: 100,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      }, {
        id: 5,
        price: '7,188.00',
        amount: 7188,
        planName: 'CloudBoost Pro Plus Yearly',
        interval: 'year',
        apiCalls: 10000000,
        storage: 100,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      }, {
        id: 6,
        price: '292.00',
        amount: 292,
        planName: 'CloudBoost Pro Monthly',
        interval: 'month',
        apiCalls: 1000000,
        storage: 10,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      }, {
        id: 7,
        price: '2,988.00',
        amount: 2988,
        planName: 'CloudBoost Pro Yearly',
        interval: 'year',
        apiCalls: 1000000,
        storage: 10,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      }, {
        id: 8,
        price: '93.00',
        amount: 93,
        planName: 'CloudBoost Basic Monthly',
        interval: 'month',
        apiCalls: 100000,
        storage: 1,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      }, {
        id: 9,
        price: '948.00',
        amount: 948,
        planName: 'CloudBoost Basic Yearly',
        interval: 'year',
        apiCalls: 100000,
        storage: 1,
        connections: 10000,
        mongoDbAccess: true,
        gbRate: 10,
        apiRate: 0.00015,
      },
    ],
  };
};
